[package]
name = "rust-feeds"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
lazy_static = "1.5.0"
rusqlite = "0.34.0"
sha2 = "0.10.8"
smol = "2.0.2"
smol-macros = "0.1.1"
textnonce = "1.0.0"
