services:
  rust-feeds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-feeds
    restart: unless-stopped
    volumes:
      - ./sqlite:/app/sqlite
    ports:
      - "2137:2137"

